library(tidyr)

dep_bn <- list(
  list(c(0, 0, 1,  0,  0,  0,  1,  0,  1),
       c(1,  1,  0,  1,  1,  1,  0,  1,  0)),
  list(
    c(0,  0,  1,  0,  0,  0,  1,  0,  1),
    c(0,  0,  1,  0,  0,  1,  0,  1,  0),
    c(0,  0,  0,  1,  0,  1,  0,  1,  0)),
  list(
    c(0,  0,  1,  0,  0,  0,  1,  0,  1)))

dep_cnt <- list(
  list(
    c(1,  1,  2,  2,  3,  3,  4,  5,  6),
    c(6,  6,  5,  5,  4,  4,  3,  2,  1)),
  list(
    c(1,  1,  2,  2,  3,  3,  4,  5,  6),
    c(6,  5,  4,  3,  3,  2,  2,  1,  1),
    c(1,  1,  2,  2,  3,  3,  4,  5,  6)),
  list(
    c(1,  1,  1,  1,  1,  1,  2,  2,  2)))

wgt <- list(
    c(1,  2,  3,  4,  5,  4,  3,  2,  1),
    c(1,  2,  3,  4,  5,  4,  3,  2,  1),
    c(1,  2,  3,  4,  5,  4,  3,  2,  1))

ind <- list(
  matrix(c(.6,.7,.8,
           .8,.7,.7,
           .7,.8,.6,
           .9,.7,.9,
           .8,.9,.6,
           .8,.5,.8,
           .2, 0,.3,
           .3,.4,.4,
           .4,.7, 0), ncol = 3, byrow = T),
  matrix(c(.9,.7,.8,
           .8,.7,.7,
           .7,.8,.9,
           .6,.5,.6,
           .6,.6,.6,
           .6,.5,.5,
           .2,.1,.3,
           .3,.4,.4,
           .4,.7,.3), ncol = 3, byrow = T),
  matrix(c(.6,.7,.8,
           .8,.7,.7,
           .7,.8,.6,
           .9,.7,.9,
           .8,.9,.6,
           .8,.5,.8,
           .2,.1,.3,
           .3,.4,.4,
           .4,.7,.3), ncol = 3, byrow = T))

ind_df <- lapply(ind, data.frame)

output <- "// GLM validation data - auto-generated by R script\n\n"
output <- c(output, "IMPORT ML_Core;\n Layout_Model := ML_Core.Types.Layout_Model;\n\n")
output <- c(output, "EXPORT unit_test_getModel_Rdata := MODULE\n")

families <- list(quasibinomial(), quasipoisson(), Gamma(), gaussian(), inverse.gaussian())
families[[5]]$family <- "invgauss"

fs <- function(x)
  format(x, scientific = F)

control <- glm.control(epsilon = 1e-8, maxit = 100, trace = F)


mdls <- list()
for (fam in families)
{
  famName <- fam$family
  mdls[[famName]] <- list()
  output <- c(output, paste0("\nEXPORT ", famName, " := DATASET([\n"))

  if (famName == 'quasibinomial')
    y <- dep_bn
  else
    y <- dep_cnt

  for (wi in 1:length(y))
  {
    mdls[[famName]][[wi]] <- list()

    output <- c(output, "{")
    output <- c(output, paste(wi, 0, 1, 3, sep = ", "), "},\n {")
    output <- c(output, paste(wi, 0, 2, 100, sep = ", "), "},\n {")
    output <- c(output, paste(wi, 0, 3, fs(1e-7), sep = ", "), "},\n {")
    output <- c(output, paste(wi, 0, 4, fs(ncol(ind_df[[wi]])), sep = ", "), "},\n {")
    output <- c(output, paste(wi, 0, 5, fs(length(y[[wi]])), sep = ", "), "},\n {")
    output <- c(output, paste(wi, 0, 6, fs(nrow(ind_df[[wi]])), sep = ", "), "}")

    for (nbr in 1:length(y[[wi]]))
    {
      # control$maxit <- maxit[[famName]][[wi]][[nbr]]

      mdls[[famName]][[wi]][[nbr]] <-
        glm(y[[wi]][[nbr]] ~ as.matrix(ind_df[[wi]]), family = fam, control = control, weights = wgt[[wi]])

      mdlSummary <- summary(mdls[[famName]][[wi]][[nbr]])

      output <- c(output, ",\n {", paste(wi, 1, nbr, mdls[[famName]][[wi]][[nbr]]$iter+1, sep = ", "), "},\n {")
      output <- c(output, paste(wi, 2, nbr, 0, sep = ", "), "},\n {")
      output <- c(output, paste(wi, 3, nbr, fs(mean((mdls[[famName]][[wi]][[nbr]]$fitted.values - y[[wi]][[nbr]])^2)), sep = ", "), "},\n {")
      output <- c(output, paste(wi, 4, nbr, fs(mdlSummary$dispersion), sep = ", "), "},\n {")
      output <- c(output, paste(wi, 5:8, nbr, fs(mdlSummary$coefficients[,1]), sep = ", ", collapse = " },\n { "), "},\n {")
      output <- c(output, paste(wi, 9:12, nbr, fs(mdlSummary$coefficients[,2]), sep = ", ", collapse = " },\n { "), "}")
    }
    if (wi != length(y))
      output <- c(output, ",\n")
  }
  output <- c(output, "\n], Layout_Model);\n\n")

}

output <- c(output, "END;")

cat(output, file = "unit_test_getModel_Rdata.ecl")


